import Head from "next/head";
import { IHomeProps } from "../interfaces/characters/characters.interface";
import Link from "next/link";
import { GetStaticProps } from "next";
import { api } from "@/services/api";
import Card from "@/components/CardCharacter";

export default function Home({ character }: IHomeProps) {
  return (
    <>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <ul>
            {character.map((char) => (
              <Card
                key={char.id}
                id={char.id}
                image={char.image}
                location={char.location}
                name={char.name}
                status={char.status}
              />
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const { data: characters } = await api.get("character", {
    params: {
      limit: 826,
      offset: 0,
    },
  });

  return {
    props: {
      character: characters.results,
    },
  };
};
