import Head from "next/head";
import { IHomeProps } from "../interfaces/characters/characters.interface";
import { GetStaticProps } from "next";
import { api } from "@/services/api";
import Card from "@/components/CardCharacter";
import Header from "@/components/Header";
import Container from "@/components/Container";
import Navbar from "@/components/NavBar";
import InputSearch from "@/components/InputFilter";
import { useState } from "react";
import { StyledMenu } from "@/components/MenuDropDown/styled";
import { TitleSearch, Main, FilterTitleSearch } from "@/styles/globalStyle";
import ListCards from "@/components/ListCards";
import SectionMainCard from "@/components/MainSectionCards";
import SectionMainFilters from "@/components/MainSectionFilters";

export default function Home({ character }: IHomeProps) {
  const [visivel, setVisible] = useState(false);
  const [status, setStatus] = useState("Personagens");

  const menuDropDown = () => {
    setVisible((visivel) => !visivel);
  };

  return (
    <>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <Container>
          <Navbar>
            <img src="../logo.png" alt="logo" />
            <button onClick={() => menuDropDown()}>{!visivel ? "Menu" : "Fechar"}</button>
            {visivel && (
              <StyledMenu>
                <button onClick={() => setStatus("Personagens")}>Personagens</button>
                <button onClick={() => setStatus("Episódios")}>Episódios</button>
                <button onClick={() => setStatus("Locais")}>Locais</button>
              </StyledMenu>
            )}
          </Navbar>
        </Container>
      </Header>
      <Container>
        <Main>
          <SectionMainFilters>
            <TitleSearch>{status}</TitleSearch>
            <InputSearch />
            <FilterTitleSearch>Filters</FilterTitleSearch>
            <button>Limpar Filtro</button>
          </SectionMainFilters>
          <SectionMainCard>
            <ListCards>
              {character.map((char) => (
                <Card
                  key={char.id}
                  id={char.id}
                  image={char.image}
                  location={char.location}
                  name={char.name}
                  status={char.status}
                />
              ))}
            </ListCards>
          </SectionMainCard>
        </Main>
      </Container>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const { data: characters } = await api.get("character", {
    params: {
      limit: 826,
      offset: 0,
    },
  });

  return {
    props: {
      character: characters.results,
    },
  };
};
